wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1653531641
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 13
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
att_type:
  desc: null
  value: dotloc
aug:
  desc: null
  value: jit
batch_size:
  desc: null
  value: 32
clip_grad:
  desc: null
  value: 1.0
cooldown_epochs:
  desc: null
  value: 10
cuda:
  desc: null
  value: true
dataset:
  desc: null
  value: modelnet40
decay_rate:
  desc: null
  value: 0.1
dropout:
  desc: null
  value: 0
droppath:
  desc: null
  value: 0
ema:
  desc: null
  value: 'True'
ema_decay:
  desc: null
  value: 0.999
emb_dims:
  desc: null
  value: 1024
epochs:
  desc: null
  value: 200
eval:
  desc: null
  value: false
exp_name:
  desc: null
  value: exp-2022.05.26_02:20
gamma:
  desc: null
  value: 3.0
k:
  desc: null
  value: 16
lgpa:
  desc: null
  value: 1
lin_bias:
  desc: null
  value: false
lr:
  desc: null
  value: 0.01
min_lr:
  desc: null
  value: 0.0001
model:
  desc: null
  value: rbf
model_path:
  desc: null
  value: ''
momentum:
  desc: null
  value: 0.9
no_cuda:
  desc: null
  value: false
num_class:
  desc: null
  value: 40
num_g:
  desc: null
  value: 16
num_points:
  desc: null
  value: 1024
patience:
  desc: null
  value: 50
sched:
  desc: null
  value: cosine
seed:
  desc: null
  value: 1
tau:
  desc: null
  value: 0.1
test_batch_size:
  desc: null
  value: 128
use_sgd:
  desc: null
  value: true
use_voting:
  desc: null
  value: false
use_wandb:
  desc: null
  value: 'True'
ver:
  desc: null
  value: hard
warmup_epochs:
  desc: null
  value: 5
warmup_lr:
  desc: null
  value: 1.0e-05
weight_decay:
  desc: null
  value: 0.001
