wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.11
    start_time: 1653718478
    t:
      1:
      - 1
      - 5
      4: 3.7.11
      5: 0.12.10
      8:
      - 5
att_type:
  desc: null
  value: dot
aug:
  desc: null
  value: 'True'
batch_size:
  desc: null
  value: 16
class_choice:
  desc: null
  value: null
clip_grad:
  desc: null
  value: 1.0
cooldown_epochs:
  desc: null
  value: 10
cuda:
  desc: null
  value: true
dataset:
  desc: null
  value: shapenetpart
decay_rate:
  desc: null
  value: 0.1
drop_points:
  desc: null
  value: 0
dropout:
  desc: null
  value: 0.5
droppath:
  desc: null
  value: 0
ema:
  desc: null
  value: 'True'
ema_decay:
  desc: null
  value: 0.999
emb_dims:
  desc: null
  value: 128
epochs:
  desc: null
  value: 200
eval:
  desc: null
  value: false
exp_name:
  desc: null
  value: exp1
gamma:
  desc: null
  value: 3
k:
  desc: null
  value: 32
lr:
  desc: null
  value: 0.05
min_lr:
  desc: null
  value: 0.0005
model:
  desc: null
  value: rbf
model_path:
  desc: null
  value: ''
momentum:
  desc: null
  value: 0.9
no_cuda:
  desc: null
  value: false
num_g:
  desc: null
  value: 32
num_points:
  desc: null
  value: 2048
optimizer:
  desc: null
  value: SGD
patience:
  desc: null
  value: 100
port:
  desc: null
  value: 11120
rank:
  desc: null
  value: 0
s_ratio:
  desc: null
  value: 0.25
sched:
  desc: null
  value: cosine
seed:
  desc: null
  value: 3925
tau:
  desc: null
  value: 1
test_batch_size:
  desc: null
  value: 16
use_sample:
  desc: null
  value: 'True'
use_wandb:
  desc: null
  value: 'True'
visu:
  desc: null
  value: ''
visu_format:
  desc: null
  value: ply
warmup_epochs:
  desc: null
  value: 5
warmup_lr:
  desc: null
  value: 5.0e-05
weight_decay:
  desc: null
  value: 0.0001
world_size:
  desc: null
  value: 4
